CREATE TABLE talents (id integer primary key, name text, email text);
INSERT INTO "talents" VALUES (1, 'Anik', 'Anik@tasawr.com');
INSERT INTO "talents" VALUES (2, 'Ashraf', 'Ashraf@tasawr.com');
INSERT INTO "talents" VALUES (3, 'Bazlur', 'Bazlur@tasawr.com');
INSERT INTO "talents" VALUES (4, 'Farhan', 'Farhan@tasawr.com');
INSERT INTO "talents" VALUES (5, 'Gazi', 'Gazi@tasawr.com');
INSERT INTO "talents" VALUES (6, 'Habib', 'Habib@tasawr.com');
INSERT INTO "talents" VALUES (7, 'Hasin', 'Hasin@tasawr.com');
INSERT INTO "talents" VALUES (8, 'Hasinur', 'Hasinur@tasawr.com');
INSERT INTO "talents" VALUES (9, 'Irfan', 'Irfan@tasawr.com');
INSERT INTO "talents" VALUES (10, 'Jhalak', 'Jhalak@tasawr.com');
INSERT INTO "talents" VALUES (11, 'Kamal', 'Kamal@tasawr.com');
INSERT INTO "talents" VALUES (12, 'Khair', 'Khair@tasawr.com');
INSERT INTO "talents" VALUES (13, 'Lenin', 'Lenin@tasawr.com');
INSERT INTO "talents" VALUES (14, 'Mahfuz', 'Mahfuz@tasawr.com');
INSERT INTO "talents" VALUES (15, 'Mosaddek', 'Mosaddek@tasawr.com');
INSERT INTO "talents" VALUES (16, 'Munshi', 'Munshi@tasawr.com');
INSERT INTO "talents" VALUES (17, 'Muntasim', 'Muntasim@tasawr.com');
INSERT INTO "talents" VALUES (18, 'Mushfiq', 'Mushfiq@tasawr.com');
INSERT INTO "talents" VALUES (19, 'Nurul', 'Nurul@tasawr.com');
INSERT INTO "talents" VALUES (20, 'Rafiqul', 'Rafiqul@tasawr.com');
INSERT INTO "talents" VALUES (21, 'Rakib', 'Rakib@tasawr.com');
INSERT INTO "talents" VALUES (22, 'Rifat', 'Rifat@tasawr.com');
INSERT INTO "talents" VALUES (23, 'Rinku', 'Rinku@tasawr.com');
INSERT INTO "talents" VALUES (24, 'Sakib', 'Sakib@tasawr.com');
INSERT INTO "talents" VALUES (25, 'Shahjahan', 'Shahjahan@tasawr.com');
INSERT INTO "talents" VALUES (26, 'Talha', 'Talha@tasawr.com');
INSERT INTO "talents" VALUES (27, 'Tanjim', 'Tanjim@tasawr.com');
INSERT INTO "talents" VALUES (28, 'Tariq', 'Tariq@tasawr.com');
INSERT INTO "talents" VALUES (29, 'Wasiqul', 'Wasiqul@tasawr.com');
INSERT INTO "talents" VALUES (30, 'Younus', 'Younus@tasawr.com');

CREATE TABLE projects (id integer primary key, name text, type text);
INSERT INTO "projects" VALUES (1, 'Moteel', 'main');
INSERT INTO "projects" VALUES (2, 'Raakib', 'main');
INSERT INTO "projects" VALUES (3, 'Al-Khudair', 'main');
INSERT INTO "projects" VALUES (4, 'Al-Khudair mobile', 'main');
INSERT INTO "projects" VALUES (5, 'OpenBravo', 'main');
INSERT INTO "projects" VALUES (6, 'Ma7mi', 'main');
INSERT INTO "projects" VALUES (7, 'HR', 'hr'); 
INSERT INTO "projects" VALUES (8, 'System Admin & Support', 'sysadmin');
INSERT INTO "projects" VALUES (9, 'Absent During Meeting', 'absent');
INSERT INTO "projects" VALUES (10, 'Absent But Informed', 'absent');
INSERT INTO "projects" VALUES (11, 'On leave', 'leave');

